// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module compute_c_sqrt_fixed_18_9_s (
        ap_clk,
        ap_rst,
        x,
        ap_return,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [17:0] x;
output  [13:0] ap_return;
input   ap_ce;

reg[13:0] ap_return;

reg   [17:0] x_read_reg_1872;
wire    ap_block_pp0_stage0_11001;
reg   [17:0] x_read_reg_1872_pp0_iter1_reg;
reg   [17:0] x_read_reg_1872_pp0_iter2_reg;
reg   [17:0] x_read_reg_1872_pp0_iter3_reg;
reg   [17:0] x_read_reg_1872_pp0_iter4_reg;
reg   [17:0] x_read_reg_1872_pp0_iter5_reg;
reg   [17:0] x_read_reg_1872_pp0_iter6_reg;
reg   [17:0] x_read_reg_1872_pp0_iter7_reg;
reg   [17:0] x_read_reg_1872_pp0_iter8_reg;
reg   [17:0] x_read_reg_1872_pp0_iter9_reg;
wire   [8:0] trunc_ln213_fu_196_p1;
reg   [8:0] trunc_ln213_reg_1877;
reg   [8:0] trunc_ln213_reg_1877_pp0_iter1_reg;
wire   [11:0] x_l_I_1_fu_236_p3;
reg   [11:0] x_l_I_1_reg_1882;
wire   [4:0] select_ln216_fu_244_p3;
reg   [4:0] select_ln216_reg_1888;
wire   [0:0] icmp_ln258_1_fu_280_p2;
reg   [0:0] icmp_ln258_1_reg_1894;
wire   [4:0] sub_ln263_fu_286_p2;
reg   [4:0] sub_ln263_reg_1900;
reg   [1:0] tmp_20_reg_1905;
reg   [1:0] tmp_20_reg_1905_pp0_iter1_reg;
wire   [4:0] res_I_3_fu_399_p3;
reg   [4:0] res_I_3_reg_1911;
wire   [0:0] icmp_ln258_3_fu_423_p2;
reg   [0:0] icmp_ln258_3_reg_1917;
wire   [11:0] x_l_I_9_fu_445_p3;
reg   [11:0] x_l_I_9_reg_1922;
wire   [4:0] res_I_5_fu_469_p3;
reg   [4:0] res_I_5_reg_1931;
reg   [4:0] res_I_5_reg_1931_pp0_iter3_reg;
reg   [4:0] res_I_5_reg_1931_pp0_iter4_reg;
reg   [4:0] res_I_5_reg_1931_pp0_iter5_reg;
reg   [4:0] res_I_5_reg_1931_pp0_iter6_reg;
reg   [4:0] res_I_5_reg_1931_pp0_iter7_reg;
reg   [4:0] res_I_5_reg_1931_pp0_iter8_reg;
reg   [4:0] res_I_5_reg_1931_pp0_iter9_reg;
wire   [0:0] or_ln295_1_fu_529_p2;
reg   [0:0] or_ln295_1_reg_1942;
wire   [11:0] x_l_I_4_fu_535_p3;
reg   [11:0] x_l_I_4_reg_1947;
wire   [9:0] x_l_FH_20_fu_542_p3;
reg   [9:0] x_l_FH_20_reg_1956;
wire   [0:0] trunc_ln283_fu_550_p1;
reg   [0:0] trunc_ln283_reg_1964;
reg   [3:0] tmp_12_reg_1969;
wire   [1:0] trunc_ln283_1_fu_564_p1;
reg   [1:0] trunc_ln283_1_reg_1974;
reg   [1:0] trunc_ln283_1_reg_1974_pp0_iter3_reg;
reg   [2:0] tmp_13_reg_1979;
reg   [2:0] tmp_13_reg_1979_pp0_iter3_reg;
wire   [2:0] trunc_ln283_2_fu_578_p1;
reg   [2:0] trunc_ln283_2_reg_1984;
reg   [2:0] trunc_ln283_2_reg_1984_pp0_iter3_reg;
reg   [1:0] tmp_14_reg_1989;
reg   [1:0] tmp_14_reg_1989_pp0_iter3_reg;
wire   [3:0] trunc_ln283_3_fu_592_p1;
reg   [3:0] trunc_ln283_3_reg_1994;
reg   [3:0] trunc_ln283_3_reg_1994_pp0_iter3_reg;
reg   [3:0] trunc_ln283_3_reg_1994_pp0_iter4_reg;
reg   [0:0] tmp_30_reg_1999;
reg   [0:0] tmp_30_reg_1999_pp0_iter3_reg;
reg   [0:0] tmp_30_reg_1999_pp0_iter4_reg;
wire   [11:0] x_l_I_15_fu_702_p3;
reg   [11:0] x_l_I_15_reg_2004;
wire   [9:0] x_l_FH_21_fu_709_p3;
reg   [9:0] x_l_FH_21_reg_2013;
wire   [9:0] res_FH_2_fu_716_p3;
reg   [9:0] res_FH_2_reg_2021;
reg   [2:0] tmp_s_reg_2027;
wire   [11:0] x_l_I_19_fu_813_p3;
reg   [11:0] x_l_I_19_reg_2032;
wire   [9:0] x_l_FH_22_fu_820_p3;
reg   [9:0] x_l_FH_22_reg_2038;
wire   [9:0] res_FH_4_fu_827_p3;
reg   [9:0] res_FH_4_reg_2043;
wire   [11:0] zext_ln295_3_fu_851_p1;
reg   [11:0] zext_ln295_3_reg_2049;
wire   [0:0] icmp_ln295_9_fu_854_p2;
reg   [0:0] icmp_ln295_9_reg_2054;
wire   [0:0] icmp_ln295_10_fu_860_p2;
reg   [0:0] icmp_ln295_10_reg_2059;
wire   [0:0] icmp_ln295_11_fu_866_p2;
reg   [0:0] icmp_ln295_11_reg_2064;
wire   [0:0] icmp_ln308_3_fu_872_p2;
reg   [0:0] icmp_ln308_3_reg_2069;
wire   [11:0] x_l_I_20_fu_878_p2;
reg   [11:0] x_l_I_20_reg_2074;
wire   [9:0] x_l_FH_7_fu_884_p2;
reg   [9:0] x_l_FH_7_reg_2079;
wire   [11:0] x_l_I_23_fu_924_p3;
reg   [11:0] x_l_I_23_reg_2084;
wire   [11:0] x_l_I_26_fu_1020_p2;
reg   [11:0] x_l_I_26_reg_2089;
wire   [0:0] or_ln295_5_fu_1036_p2;
reg   [0:0] or_ln295_5_reg_2094;
wire   [9:0] x_l_FH_24_fu_1042_p3;
reg   [9:0] x_l_FH_24_reg_2099;
wire   [9:0] res_FH_8_fu_1050_p3;
reg   [9:0] res_FH_8_reg_2106;
reg   [0:0] tmp_32_reg_2112;
reg   [4:0] tmp_16_reg_2117;
wire   [11:0] x_l_I_30_fu_1151_p3;
reg   [11:0] x_l_I_30_reg_2122;
wire   [9:0] x_l_FH_25_fu_1159_p3;
reg   [9:0] x_l_FH_25_reg_2129;
wire   [9:0] x_l_FL_8_fu_1166_p3;
reg   [9:0] x_l_FL_8_reg_2138;
wire   [9:0] res_FH_10_fu_1174_p3;
reg   [9:0] res_FH_10_reg_2145;
reg   [3:0] tmp_18_reg_2151;
wire   [9:0] mul_FL_1_fu_1201_p3;
reg   [9:0] mul_FL_1_reg_2156;
wire   [0:0] delta_fu_1209_p2;
reg   [0:0] delta_reg_2162;
wire   [11:0] x_l_I_33_fu_1327_p3;
reg   [11:0] x_l_I_33_reg_2168;
wire   [9:0] x_l_FH_26_fu_1335_p3;
reg   [9:0] x_l_FH_26_reg_2175;
wire   [9:0] x_l_FL_9_fu_1342_p3;
reg   [9:0] x_l_FL_9_reg_2184;
wire   [9:0] res_FH_12_fu_1349_p3;
reg   [9:0] res_FH_12_reg_2191;
reg   [2:0] tmp_21_reg_2197;
wire   [9:0] mul_FL_2_fu_1376_p3;
reg   [9:0] mul_FL_2_reg_2202;
wire   [0:0] delta_1_fu_1384_p2;
reg   [0:0] delta_1_reg_2208;
wire   [11:0] x_l_I_36_fu_1510_p3;
reg   [11:0] x_l_I_36_reg_2214;
wire   [9:0] x_l_FH_27_fu_1518_p3;
reg   [9:0] x_l_FH_27_reg_2221;
wire   [9:0] x_l_FL_10_fu_1525_p3;
reg   [9:0] x_l_FL_10_reg_2230;
wire   [9:0] res_FH_14_fu_1532_p3;
reg   [9:0] res_FH_14_reg_2237;
reg   [1:0] tmp_22_reg_2243;
wire   [9:0] mul_FL_3_fu_1559_p3;
reg   [9:0] mul_FL_3_reg_2248;
wire   [0:0] delta_2_fu_1567_p2;
reg   [0:0] delta_2_reg_2254;
wire   [0:0] or_ln295_11_fu_1687_p2;
reg   [0:0] or_ln295_11_reg_2260;
wire   [9:0] x_l_FH_17_fu_1693_p3;
reg   [9:0] x_l_FH_17_reg_2265;
wire   [9:0] res_FH_16_fu_1707_p3;
reg   [9:0] res_FH_16_reg_2271;
reg   [0:0] tmp_37_reg_2277;
wire   [0:0] icmp_ln295_29_fu_1734_p2;
reg   [0:0] icmp_ln295_29_reg_2282;
wire   [0:0] icmp_ln295_32_fu_1740_p2;
reg   [0:0] icmp_ln295_32_reg_2287;
wire    ap_block_pp0_stage0;
wire   [8:0] tmp_3_fu_182_p4;
wire   [2:0] tmp_1_fu_200_p4;
wire   [3:0] zext_ln258_fu_210_p1;
wire   [11:0] zext_ln212_fu_192_p1;
wire   [3:0] add_ln263_fu_220_p2;
wire   [0:0] icmp_ln258_fu_214_p2;
wire   [11:0] x_l_I_fu_226_p4;
wire   [1:0] select_ln216_1_fu_252_p3;
wire   [2:0] tmp_7_fu_260_p3;
wire   [4:0] tmp_2_fu_268_p3;
wire   [4:0] zext_ln258_1_fu_276_p1;
wire   [11:0] x_l_I_2_fu_302_p4;
wire   [4:0] res_I_fu_310_p4;
wire   [4:0] res_I_1_fu_325_p3;
wire   [3:0] tmp_5_fu_331_p3;
wire   [11:0] x_l_I_5_fu_319_p3;
wire   [4:0] tmp_4_fu_339_p3;
wire   [5:0] tmp_8_fu_347_p3;
wire   [5:0] zext_ln258_2_fu_355_p1;
wire   [5:0] sub_ln263_1_fu_365_p2;
wire   [0:0] icmp_ln258_2_fu_359_p2;
wire   [11:0] x_l_I_6_fu_371_p4;
wire   [4:0] res_I_2_fu_381_p4;
wire   [11:0] x_l_I_7_fu_391_p3;
wire   [5:0] tmp_6_fu_407_p3;
wire   [6:0] trunc_ln258_fu_415_p1;
wire   [6:0] zext_ln258_3_fu_419_p1;
wire   [6:0] sub_ln263_2_fu_429_p2;
wire   [11:0] x_l_I_8_fu_435_p4;
wire   [4:0] res_I_4_fu_460_p4;
wire   [11:0] zext_ln295_fu_475_p1;
wire   [0:0] icmp_ln295_1_fu_484_p2;
wire   [0:0] icmp_ln295_2_fu_489_p2;
wire   [0:0] icmp_ln308_fu_500_p2;
wire   [11:0] x_l_I_10_fu_505_p2;
wire   [9:0] x_l_FH_19_fu_453_p3;
wire   [11:0] x_l_I_3_fu_510_p3;
wire   [0:0] icmp_ln295_fu_479_p2;
wire   [0:0] and_ln295_fu_494_p2;
wire   [11:0] x_l_I_11_fu_523_p2;
wire   [9:0] x_l_FH_fu_517_p2;
wire   [9:0] res_FH_fu_604_p3;
wire   [1:0] tmp_9_fu_611_p3;
wire   [11:0] zext_ln295_1_fu_628_p1;
wire   [9:0] mul_FH_fu_619_p4;
wire   [0:0] icmp_ln295_5_fu_641_p2;
wire   [0:0] icmp_ln295_4_fu_636_p2;
wire   [0:0] xor_ln295_fu_646_p2;
wire   [0:0] icmp_ln308_1_fu_658_p2;
wire   [11:0] x_l_I_12_fu_663_p2;
wire   [11:0] x_l_I_13_fu_668_p3;
wire   [0:0] icmp_ln295_3_fu_631_p2;
wire   [0:0] and_ln295_1_fu_652_p2;
wire   [0:0] or_ln295_2_fu_696_p2;
wire   [11:0] x_l_I_14_fu_680_p2;
wire   [9:0] x_l_FH_3_fu_675_p2;
wire   [9:0] res_FH_1_fu_686_p4;
wire   [11:0] zext_ln295_2_fu_740_p1;
wire   [9:0] mul_FH_1_fu_732_p4;
wire   [0:0] icmp_ln295_8_fu_753_p2;
wire   [0:0] icmp_ln295_7_fu_748_p2;
wire   [0:0] xor_ln295_1_fu_758_p2;
wire   [0:0] icmp_ln308_2_fu_770_p2;
wire   [11:0] x_l_I_16_fu_775_p2;
wire   [11:0] x_l_I_17_fu_780_p3;
wire   [0:0] icmp_ln295_6_fu_743_p2;
wire   [0:0] and_ln295_2_fu_764_p2;
wire   [0:0] or_ln295_3_fu_807_p2;
wire   [11:0] x_l_I_18_fu_792_p2;
wire   [9:0] x_l_FH_5_fu_787_p2;
wire   [9:0] res_FH_3_fu_798_p4;
wire   [3:0] tmp_10_fu_834_p3;
wire   [9:0] mul_FH_2_fu_842_p4;
wire   [0:0] xor_ln295_2_fu_890_p2;
wire   [11:0] x_l_I_21_fu_900_p3;
wire   [0:0] and_ln295_3_fu_895_p2;
wire   [0:0] or_ln295_4_fu_919_p2;
wire   [11:0] x_l_I_22_fu_905_p2;
wire   [9:0] res_FH_5_fu_910_p4;
wire   [9:0] res_FH_6_fu_937_p3;
wire   [4:0] tmp_11_fu_944_p3;
wire   [11:0] zext_ln295_4_fu_961_p1;
wire   [9:0] x_l_FH_23_fu_931_p3;
wire   [9:0] mul_FH_3_fu_952_p4;
wire   [0:0] icmp_ln295_14_fu_976_p2;
wire   [0:0] icmp_ln295_13_fu_970_p2;
wire   [0:0] xor_ln295_3_fu_982_p2;
wire   [0:0] icmp_ln308_4_fu_994_p2;
wire   [11:0] x_l_I_24_fu_1000_p2;
wire   [11:0] x_l_I_25_fu_1006_p3;
wire   [0:0] icmp_ln295_12_fu_964_p2;
wire   [0:0] and_ln295_4_fu_988_p2;
wire   [9:0] x_l_FH_9_fu_1014_p2;
wire   [9:0] res_FH_7_fu_1026_p4;
wire   [11:0] x_l_I_27_fu_1076_p3;
wire   [9:0] mul_FH_4_fu_1081_p3;
wire   [0:0] icmp_ln295_15_fu_1094_p2;
wire   [0:0] icmp_ln295_16_fu_1100_p2;
wire   [9:0] mul_FL_fu_1087_p3;
wire   [11:0] x_l_I_28_fu_1117_p2;
wire   [9:0] xor_ln319_fu_1131_p2;
wire   [0:0] or_ln295_fu_1105_p2;
wire   [11:0] x_l_I_29_fu_1123_p3;
wire   [9:0] x_l_FH_11_fu_1137_p2;
wire   [9:0] x_l_FL_fu_1111_p2;
wire   [9:0] res_FH_9_fu_1142_p4;
wire   [2:0] tmp_15_fu_1181_p4;
wire   [8:0] mul_FH_5_fu_1215_p3;
wire   [9:0] zext_ln285_fu_1221_p1;
wire   [0:0] icmp_ln295_20_fu_1240_p2;
wire   [0:0] icmp_ln295_19_fu_1235_p2;
wire   [0:0] xor_ln295_4_fu_1244_p2;
wire   [0:0] icmp_ln308_5_fu_1260_p2;
wire   [0:0] and_ln308_fu_1265_p2;
wire   [0:0] or_ln308_fu_1270_p2;
wire   [11:0] x_l_I_31_fu_1276_p2;
wire   [9:0] p_neg7_fu_1288_p3;
wire   [9:0] sub_ln319_fu_1295_p2;
wire   [0:0] icmp_ln295_18_fu_1230_p2;
wire   [0:0] and_ln295_5_fu_1250_p2;
wire   [0:0] or_ln295_6_fu_1315_p2;
wire   [0:0] icmp_ln295_17_fu_1225_p2;
wire   [0:0] or_ln295_7_fu_1321_p2;
wire   [11:0] x_l_I_32_fu_1281_p3;
wire   [9:0] x_l_FH_13_fu_1301_p2;
wire   [9:0] x_l_FL_2_fu_1256_p2;
wire   [9:0] res_FH_11_fu_1306_p4;
wire   [4:0] tmp_17_fu_1356_p4;
wire   [7:0] mul_FH_6_fu_1390_p3;
wire   [9:0] zext_ln285_1_fu_1396_p1;
wire   [0:0] icmp_ln295_24_fu_1419_p2;
wire   [0:0] icmp_ln295_23_fu_1414_p2;
wire   [0:0] xor_ln295_5_fu_1423_p2;
wire   [0:0] icmp_ln308_6_fu_1439_p2;
wire   [0:0] and_ln308_1_fu_1444_p2;
wire   [0:0] or_ln308_1_fu_1449_p2;
wire   [11:0] x_l_I_34_fu_1455_p2;
wire   [8:0] select_ln319_fu_1467_p3;
wire   [8:0] zext_ln285_2_fu_1400_p1;
wire   [8:0] sub_ln319_1_fu_1474_p2;
wire  signed [9:0] sext_ln319_fu_1480_p1;
wire   [0:0] icmp_ln295_22_fu_1409_p2;
wire   [0:0] and_ln295_6_fu_1429_p2;
wire   [0:0] or_ln295_8_fu_1498_p2;
wire   [0:0] icmp_ln295_21_fu_1404_p2;
wire   [0:0] or_ln295_9_fu_1504_p2;
wire   [11:0] x_l_I_35_fu_1460_p3;
wire   [9:0] x_l_FH_15_fu_1484_p2;
wire   [9:0] x_l_FL_4_fu_1435_p2;
wire   [9:0] res_FH_13_fu_1489_p4;
wire   [6:0] tmp_19_fu_1539_p4;
wire   [6:0] mul_FH_7_fu_1573_p3;
wire   [9:0] zext_ln285_3_fu_1579_p1;
wire   [0:0] icmp_ln295_28_fu_1602_p2;
wire   [0:0] icmp_ln295_27_fu_1597_p2;
wire   [0:0] xor_ln295_6_fu_1606_p2;
wire   [0:0] icmp_ln308_7_fu_1622_p2;
wire   [0:0] and_ln308_2_fu_1627_p2;
wire   [0:0] or_ln308_2_fu_1632_p2;
wire   [11:0] x_l_I_37_fu_1638_p2;
wire   [7:0] select_ln319_1_fu_1650_p3;
wire   [7:0] zext_ln285_4_fu_1583_p1;
wire   [7:0] sub_ln319_2_fu_1657_p2;
wire  signed [9:0] sext_ln319_1_fu_1663_p1;
wire   [0:0] icmp_ln295_26_fu_1592_p2;
wire   [0:0] and_ln295_7_fu_1612_p2;
wire   [0:0] or_ln295_10_fu_1681_p2;
wire   [0:0] icmp_ln295_25_fu_1587_p2;
wire   [9:0] x_l_FH_18_fu_1667_p2;
wire   [9:0] x_l_FL_6_fu_1618_p2;
wire   [9:0] res_FH_15_fu_1672_p4;
wire   [8:0] trunc_ln283_4_fu_1714_p1;
wire   [11:0] x_l_I_38_fu_1643_p3;
wire   [9:0] x_l_FL_7_fu_1700_p3;
wire   [9:0] mul_FL_4_fu_1718_p3;
wire   [5:0] mul_FH_8_fu_1753_p3;
wire   [9:0] zext_ln285_5_fu_1759_p1;
wire   [0:0] icmp_ln295_31_fu_1772_p2;
wire   [0:0] xor_ln295_7_fu_1777_p2;
wire   [0:0] icmp_ln295_30_fu_1767_p2;
wire   [0:0] and_ln295_8_fu_1782_p2;
wire   [0:0] or_ln295_12_fu_1797_p2;
wire   [0:0] and_ln295_9_fu_1763_p2;
wire   [0:0] or_ln295_13_fu_1803_p2;
wire   [9:0] res_FH_17_fu_1788_p4;
wire   [9:0] res_FH_18_fu_1809_p3;
wire   [10:0] zext_ln338_fu_1816_p1;
wire   [10:0] add_ln338_fu_1820_p2;
wire   [0:0] tmp_39_fu_1826_p3;
wire   [4:0] res_I_6_fu_1834_p2;
wire   [4:0] res_I_7_fu_1839_p3;
wire   [8:0] tmp_23_fu_1846_p4;
wire   [0:0] tmp_fu_1746_p3;
wire   [13:0] lshr_ln345_cast_fu_1856_p3;
wire   [13:0] agg_result_0_fu_1864_p3;
reg    ap_ce_reg;
reg   [17:0] x_int_reg;
reg   [13:0] ap_return_int_reg;

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_int_reg <= agg_result_0_fu_1864_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce_reg) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        delta_1_reg_2208 <= delta_1_fu_1384_p2;
        delta_2_reg_2254 <= delta_2_fu_1567_p2;
        delta_reg_2162 <= delta_fu_1209_p2;
        icmp_ln258_1_reg_1894 <= icmp_ln258_1_fu_280_p2;
        icmp_ln258_3_reg_1917 <= icmp_ln258_3_fu_423_p2;
        icmp_ln295_10_reg_2059 <= icmp_ln295_10_fu_860_p2;
        icmp_ln295_11_reg_2064 <= icmp_ln295_11_fu_866_p2;
        icmp_ln295_29_reg_2282 <= icmp_ln295_29_fu_1734_p2;
        icmp_ln295_32_reg_2287 <= icmp_ln295_32_fu_1740_p2;
        icmp_ln295_9_reg_2054 <= icmp_ln295_9_fu_854_p2;
        icmp_ln308_3_reg_2069 <= icmp_ln308_3_fu_872_p2;
        mul_FL_1_reg_2156[9 : 7] <= mul_FL_1_fu_1201_p3[9 : 7];
        mul_FL_2_reg_2202[9 : 5] <= mul_FL_2_fu_1376_p3[9 : 5];
        mul_FL_3_reg_2248[9 : 3] <= mul_FL_3_fu_1559_p3[9 : 3];
        or_ln295_11_reg_2260 <= or_ln295_11_fu_1687_p2;
        or_ln295_1_reg_1942 <= or_ln295_1_fu_529_p2;
        or_ln295_5_reg_2094 <= or_ln295_5_fu_1036_p2;
        res_FH_10_reg_2145 <= res_FH_10_fu_1174_p3;
        res_FH_12_reg_2191 <= res_FH_12_fu_1349_p3;
        res_FH_14_reg_2237 <= res_FH_14_fu_1532_p3;
        res_FH_16_reg_2271 <= res_FH_16_fu_1707_p3;
        res_FH_2_reg_2021 <= res_FH_2_fu_716_p3;
        res_FH_4_reg_2043 <= res_FH_4_fu_827_p3;
        res_FH_8_reg_2106 <= res_FH_8_fu_1050_p3;
        res_I_3_reg_1911 <= res_I_3_fu_399_p3;
        res_I_5_reg_1931 <= res_I_5_fu_469_p3;
        res_I_5_reg_1931_pp0_iter3_reg <= res_I_5_reg_1931;
        res_I_5_reg_1931_pp0_iter4_reg <= res_I_5_reg_1931_pp0_iter3_reg;
        res_I_5_reg_1931_pp0_iter5_reg <= res_I_5_reg_1931_pp0_iter4_reg;
        res_I_5_reg_1931_pp0_iter6_reg <= res_I_5_reg_1931_pp0_iter5_reg;
        res_I_5_reg_1931_pp0_iter7_reg <= res_I_5_reg_1931_pp0_iter6_reg;
        res_I_5_reg_1931_pp0_iter8_reg <= res_I_5_reg_1931_pp0_iter7_reg;
        res_I_5_reg_1931_pp0_iter9_reg <= res_I_5_reg_1931_pp0_iter8_reg;
        select_ln216_reg_1888[3] <= select_ln216_fu_244_p3[3];
        sub_ln263_reg_1900 <= sub_ln263_fu_286_p2;
        tmp_12_reg_1969 <= {{res_I_5_fu_469_p3[4:1]}};
        tmp_13_reg_1979 <= {{res_I_5_fu_469_p3[4:2]}};
        tmp_13_reg_1979_pp0_iter3_reg <= tmp_13_reg_1979;
        tmp_14_reg_1989 <= {{res_I_5_fu_469_p3[4:3]}};
        tmp_14_reg_1989_pp0_iter3_reg <= tmp_14_reg_1989;
        tmp_16_reg_2117 <= {{res_FH_8_fu_1050_p3[9:5]}};
        tmp_18_reg_2151 <= {{res_FH_10_fu_1174_p3[9:6]}};
        tmp_20_reg_1905 <= {{x_int_reg[8:7]}};
        tmp_20_reg_1905_pp0_iter1_reg <= tmp_20_reg_1905;
        tmp_21_reg_2197 <= {{res_FH_12_fu_1349_p3[9:7]}};
        tmp_22_reg_2243 <= {{res_FH_14_fu_1532_p3[9:8]}};
        tmp_30_reg_1999 <= res_I_5_fu_469_p3[32'd4];
        tmp_30_reg_1999_pp0_iter3_reg <= tmp_30_reg_1999;
        tmp_30_reg_1999_pp0_iter4_reg <= tmp_30_reg_1999_pp0_iter3_reg;
        tmp_32_reg_2112 <= res_FH_8_fu_1050_p3[32'd4];
        tmp_37_reg_2277 <= res_FH_16_fu_1707_p3[32'd9];
        tmp_s_reg_2027 <= {{res_FH_2_fu_716_p3[9:7]}};
        trunc_ln213_reg_1877 <= trunc_ln213_fu_196_p1;
        trunc_ln213_reg_1877_pp0_iter1_reg <= trunc_ln213_reg_1877;
        trunc_ln283_1_reg_1974 <= trunc_ln283_1_fu_564_p1;
        trunc_ln283_1_reg_1974_pp0_iter3_reg <= trunc_ln283_1_reg_1974;
        trunc_ln283_2_reg_1984 <= trunc_ln283_2_fu_578_p1;
        trunc_ln283_2_reg_1984_pp0_iter3_reg <= trunc_ln283_2_reg_1984;
        trunc_ln283_3_reg_1994 <= trunc_ln283_3_fu_592_p1;
        trunc_ln283_3_reg_1994_pp0_iter3_reg <= trunc_ln283_3_reg_1994;
        trunc_ln283_3_reg_1994_pp0_iter4_reg <= trunc_ln283_3_reg_1994_pp0_iter3_reg;
        trunc_ln283_reg_1964 <= trunc_ln283_fu_550_p1;
        x_l_FH_17_reg_2265 <= x_l_FH_17_fu_1693_p3;
        x_l_FH_20_reg_1956[9 : 1] <= x_l_FH_20_fu_542_p3[9 : 1];
        x_l_FH_21_reg_2013[9 : 1] <= x_l_FH_21_fu_709_p3[9 : 1];
        x_l_FH_22_reg_2038[9 : 1] <= x_l_FH_22_fu_820_p3[9 : 1];
        x_l_FH_24_reg_2099 <= x_l_FH_24_fu_1042_p3;
        x_l_FH_25_reg_2129 <= x_l_FH_25_fu_1159_p3;
        x_l_FH_26_reg_2175 <= x_l_FH_26_fu_1335_p3;
        x_l_FH_27_reg_2221 <= x_l_FH_27_fu_1518_p3;
        x_l_FH_7_reg_2079[9 : 1] <= x_l_FH_7_fu_884_p2[9 : 1];
        x_l_FL_10_reg_2230[9 : 4] <= x_l_FL_10_fu_1525_p3[9 : 4];
        x_l_FL_8_reg_2138[9 : 8] <= x_l_FL_8_fu_1166_p3[9 : 8];
        x_l_FL_9_reg_2184[9 : 6] <= x_l_FL_9_fu_1342_p3[9 : 6];
        x_l_I_15_reg_2004 <= x_l_I_15_fu_702_p3;
        x_l_I_19_reg_2032 <= x_l_I_19_fu_813_p3;
        x_l_I_1_reg_1882 <= x_l_I_1_fu_236_p3;
        x_l_I_20_reg_2074 <= x_l_I_20_fu_878_p2;
        x_l_I_23_reg_2084 <= x_l_I_23_fu_924_p3;
        x_l_I_26_reg_2089 <= x_l_I_26_fu_1020_p2;
        x_l_I_30_reg_2122 <= x_l_I_30_fu_1151_p3;
        x_l_I_33_reg_2168 <= x_l_I_33_fu_1327_p3;
        x_l_I_36_reg_2214 <= x_l_I_36_fu_1510_p3;
        x_l_I_4_reg_1947 <= x_l_I_4_fu_535_p3;
        x_l_I_9_reg_1922 <= x_l_I_9_fu_445_p3;
        x_read_reg_1872 <= x_int_reg;
        x_read_reg_1872_pp0_iter1_reg <= x_read_reg_1872;
        x_read_reg_1872_pp0_iter2_reg <= x_read_reg_1872_pp0_iter1_reg;
        x_read_reg_1872_pp0_iter3_reg <= x_read_reg_1872_pp0_iter2_reg;
        x_read_reg_1872_pp0_iter4_reg <= x_read_reg_1872_pp0_iter3_reg;
        x_read_reg_1872_pp0_iter5_reg <= x_read_reg_1872_pp0_iter4_reg;
        x_read_reg_1872_pp0_iter6_reg <= x_read_reg_1872_pp0_iter5_reg;
        x_read_reg_1872_pp0_iter7_reg <= x_read_reg_1872_pp0_iter6_reg;
        x_read_reg_1872_pp0_iter8_reg <= x_read_reg_1872_pp0_iter7_reg;
        x_read_reg_1872_pp0_iter9_reg <= x_read_reg_1872_pp0_iter8_reg;
        zext_ln295_3_reg_2049[1 : 0] <= zext_ln295_3_fu_851_p1[1 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce)) begin
        x_int_reg <= x;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return = ap_return_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return = agg_result_0_fu_1864_p3;
    end else begin
        ap_return = 'bx;
    end
end

assign add_ln263_fu_220_p2 = ($signed(zext_ln258_fu_210_p1) + $signed(4'd15));

assign add_ln338_fu_1820_p2 = (zext_ln338_fu_1816_p1 + 11'd1);

assign agg_result_0_fu_1864_p3 = ((tmp_fu_1746_p3[0:0] == 1'b1) ? 14'd0 : lshr_ln345_cast_fu_1856_p3);

assign and_ln295_1_fu_652_p2 = (xor_ln295_fu_646_p2 & icmp_ln295_4_fu_636_p2);

assign and_ln295_2_fu_764_p2 = (xor_ln295_1_fu_758_p2 & icmp_ln295_7_fu_748_p2);

assign and_ln295_3_fu_895_p2 = (xor_ln295_2_fu_890_p2 & icmp_ln295_10_reg_2059);

assign and_ln295_4_fu_988_p2 = (xor_ln295_3_fu_982_p2 & icmp_ln295_13_fu_970_p2);

assign and_ln295_5_fu_1250_p2 = (xor_ln295_4_fu_1244_p2 & icmp_ln295_19_fu_1235_p2);

assign and_ln295_6_fu_1429_p2 = (xor_ln295_5_fu_1423_p2 & icmp_ln295_23_fu_1414_p2);

assign and_ln295_7_fu_1612_p2 = (xor_ln295_6_fu_1606_p2 & icmp_ln295_27_fu_1597_p2);

assign and_ln295_8_fu_1782_p2 = (xor_ln295_7_fu_1777_p2 & icmp_ln295_31_fu_1772_p2);

assign and_ln295_9_fu_1763_p2 = (or_ln295_11_reg_2260 & icmp_ln295_29_reg_2282);

assign and_ln295_fu_494_p2 = (icmp_ln295_2_fu_489_p2 & icmp_ln295_1_fu_484_p2);

assign and_ln308_1_fu_1444_p2 = (icmp_ln295_23_fu_1414_p2 & delta_1_reg_2208);

assign and_ln308_2_fu_1627_p2 = (icmp_ln295_27_fu_1597_p2 & delta_2_reg_2254);

assign and_ln308_fu_1265_p2 = (icmp_ln295_19_fu_1235_p2 & delta_reg_2162);

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign delta_1_fu_1384_p2 = ((x_l_FL_9_fu_1342_p3 < mul_FL_2_fu_1376_p3) ? 1'b1 : 1'b0);

assign delta_2_fu_1567_p2 = ((x_l_FL_10_fu_1525_p3 < mul_FL_3_fu_1559_p3) ? 1'b1 : 1'b0);

assign delta_fu_1209_p2 = ((x_l_FL_8_fu_1166_p3 < mul_FL_1_fu_1201_p3) ? 1'b1 : 1'b0);

assign icmp_ln258_1_fu_280_p2 = ((tmp_2_fu_268_p3 < zext_ln258_1_fu_276_p1) ? 1'b1 : 1'b0);

assign icmp_ln258_2_fu_359_p2 = ((tmp_8_fu_347_p3 < zext_ln258_2_fu_355_p1) ? 1'b1 : 1'b0);

assign icmp_ln258_3_fu_423_p2 = ((trunc_ln258_fu_415_p1 < zext_ln258_3_fu_419_p1) ? 1'b1 : 1'b0);

assign icmp_ln258_fu_214_p2 = ((tmp_1_fu_200_p4 == 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln295_10_fu_860_p2 = ((x_l_I_19_fu_813_p3 == zext_ln295_3_fu_851_p1) ? 1'b1 : 1'b0);

assign icmp_ln295_11_fu_866_p2 = ((x_l_FH_22_fu_820_p3 < mul_FH_2_fu_842_p4) ? 1'b1 : 1'b0);

assign icmp_ln295_12_fu_964_p2 = ((x_l_I_23_fu_924_p3 > zext_ln295_4_fu_961_p1) ? 1'b1 : 1'b0);

assign icmp_ln295_13_fu_970_p2 = ((x_l_I_23_fu_924_p3 == zext_ln295_4_fu_961_p1) ? 1'b1 : 1'b0);

assign icmp_ln295_14_fu_976_p2 = ((x_l_FH_23_fu_931_p3 < mul_FH_3_fu_952_p4) ? 1'b1 : 1'b0);

assign icmp_ln295_15_fu_1094_p2 = ((x_l_I_27_fu_1076_p3 != 12'd0) ? 1'b1 : 1'b0);

assign icmp_ln295_16_fu_1100_p2 = ((x_l_FH_24_reg_2099 > mul_FH_4_fu_1081_p3) ? 1'b1 : 1'b0);

assign icmp_ln295_17_fu_1225_p2 = ((x_l_I_30_reg_2122 != 12'd0) ? 1'b1 : 1'b0);

assign icmp_ln295_18_fu_1230_p2 = ((x_l_FH_25_reg_2129 > zext_ln285_fu_1221_p1) ? 1'b1 : 1'b0);

assign icmp_ln295_19_fu_1235_p2 = ((x_l_FH_25_reg_2129 == zext_ln285_fu_1221_p1) ? 1'b1 : 1'b0);

assign icmp_ln295_1_fu_484_p2 = ((x_l_I_9_reg_1922 == zext_ln295_fu_475_p1) ? 1'b1 : 1'b0);

assign icmp_ln295_20_fu_1240_p2 = ((x_l_FL_8_reg_2138 < mul_FL_1_reg_2156) ? 1'b1 : 1'b0);

assign icmp_ln295_21_fu_1404_p2 = ((x_l_I_33_reg_2168 != 12'd0) ? 1'b1 : 1'b0);

assign icmp_ln295_22_fu_1409_p2 = ((x_l_FH_26_reg_2175 > zext_ln285_1_fu_1396_p1) ? 1'b1 : 1'b0);

assign icmp_ln295_23_fu_1414_p2 = ((x_l_FH_26_reg_2175 == zext_ln285_1_fu_1396_p1) ? 1'b1 : 1'b0);

assign icmp_ln295_24_fu_1419_p2 = ((x_l_FL_9_reg_2184 < mul_FL_2_reg_2202) ? 1'b1 : 1'b0);

assign icmp_ln295_25_fu_1587_p2 = ((x_l_I_36_reg_2214 != 12'd0) ? 1'b1 : 1'b0);

assign icmp_ln295_26_fu_1592_p2 = ((x_l_FH_27_reg_2221 > zext_ln285_3_fu_1579_p1) ? 1'b1 : 1'b0);

assign icmp_ln295_27_fu_1597_p2 = ((x_l_FH_27_reg_2221 == zext_ln285_3_fu_1579_p1) ? 1'b1 : 1'b0);

assign icmp_ln295_28_fu_1602_p2 = ((x_l_FL_10_reg_2230 < mul_FL_3_reg_2248) ? 1'b1 : 1'b0);

assign icmp_ln295_29_fu_1734_p2 = ((x_l_I_38_fu_1643_p3 != 12'd0) ? 1'b1 : 1'b0);

assign icmp_ln295_2_fu_489_p2 = ((tmp_20_reg_1905_pp0_iter1_reg != 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln295_30_fu_1767_p2 = ((x_l_FH_17_reg_2265 > zext_ln285_5_fu_1759_p1) ? 1'b1 : 1'b0);

assign icmp_ln295_31_fu_1772_p2 = ((x_l_FH_17_reg_2265 == zext_ln285_5_fu_1759_p1) ? 1'b1 : 1'b0);

assign icmp_ln295_32_fu_1740_p2 = ((x_l_FL_7_fu_1700_p3 < mul_FL_4_fu_1718_p3) ? 1'b1 : 1'b0);

assign icmp_ln295_3_fu_631_p2 = ((x_l_I_4_reg_1947 > zext_ln295_1_fu_628_p1) ? 1'b1 : 1'b0);

assign icmp_ln295_4_fu_636_p2 = ((x_l_I_4_reg_1947 == zext_ln295_1_fu_628_p1) ? 1'b1 : 1'b0);

assign icmp_ln295_5_fu_641_p2 = ((x_l_FH_20_reg_1956 < mul_FH_fu_619_p4) ? 1'b1 : 1'b0);

assign icmp_ln295_6_fu_743_p2 = ((x_l_I_15_reg_2004 > zext_ln295_2_fu_740_p1) ? 1'b1 : 1'b0);

assign icmp_ln295_7_fu_748_p2 = ((x_l_I_15_reg_2004 == zext_ln295_2_fu_740_p1) ? 1'b1 : 1'b0);

assign icmp_ln295_8_fu_753_p2 = ((x_l_FH_21_reg_2013 < mul_FH_1_fu_732_p4) ? 1'b1 : 1'b0);

assign icmp_ln295_9_fu_854_p2 = ((x_l_I_19_fu_813_p3 > zext_ln295_3_fu_851_p1) ? 1'b1 : 1'b0);

assign icmp_ln295_fu_479_p2 = ((x_l_I_9_reg_1922 > zext_ln295_fu_475_p1) ? 1'b1 : 1'b0);

assign icmp_ln308_1_fu_658_p2 = ((x_l_FH_20_reg_1956 < mul_FH_fu_619_p4) ? 1'b1 : 1'b0);

assign icmp_ln308_2_fu_770_p2 = ((x_l_FH_21_reg_2013 < mul_FH_1_fu_732_p4) ? 1'b1 : 1'b0);

assign icmp_ln308_3_fu_872_p2 = ((x_l_FH_22_fu_820_p3 < mul_FH_2_fu_842_p4) ? 1'b1 : 1'b0);

assign icmp_ln308_4_fu_994_p2 = ((x_l_FH_23_fu_931_p3 < mul_FH_3_fu_952_p4) ? 1'b1 : 1'b0);

assign icmp_ln308_5_fu_1260_p2 = ((x_l_FH_25_reg_2129 < zext_ln285_fu_1221_p1) ? 1'b1 : 1'b0);

assign icmp_ln308_6_fu_1439_p2 = ((x_l_FH_26_reg_2175 < zext_ln285_1_fu_1396_p1) ? 1'b1 : 1'b0);

assign icmp_ln308_7_fu_1622_p2 = ((x_l_FH_27_reg_2221 < zext_ln285_3_fu_1579_p1) ? 1'b1 : 1'b0);

assign icmp_ln308_fu_500_p2 = ((tmp_20_reg_1905_pp0_iter1_reg == 2'd0) ? 1'b1 : 1'b0);

assign lshr_ln345_cast_fu_1856_p3 = {{res_I_7_fu_1839_p3}, {tmp_23_fu_1846_p4}};

assign mul_FH_1_fu_732_p4 = {{{trunc_ln283_1_reg_1974_pp0_iter3_reg}, {tmp_s_reg_2027}}, {5'd16}};

assign mul_FH_2_fu_842_p4 = {{{trunc_ln283_2_reg_1984_pp0_iter3_reg}, {tmp_10_fu_834_p3}}, {3'd4}};

assign mul_FH_3_fu_952_p4 = {{{trunc_ln283_3_reg_1994_pp0_iter4_reg}, {tmp_11_fu_944_p3}}, {1'd1}};

assign mul_FH_4_fu_1081_p3 = {{res_I_5_reg_1931_pp0_iter5_reg}, {tmp_16_reg_2117}};

assign mul_FH_5_fu_1215_p3 = {{res_I_5_reg_1931_pp0_iter6_reg}, {tmp_18_reg_2151}};

assign mul_FH_6_fu_1390_p3 = {{res_I_5_reg_1931_pp0_iter7_reg}, {tmp_21_reg_2197}};

assign mul_FH_7_fu_1573_p3 = {{res_I_5_reg_1931_pp0_iter8_reg}, {tmp_22_reg_2243}};

assign mul_FH_8_fu_1753_p3 = {{res_I_5_reg_1931_pp0_iter9_reg}, {tmp_37_reg_2277}};

assign mul_FH_fu_619_p4 = {{{trunc_ln283_reg_1964}, {tmp_9_fu_611_p3}}, {7'd64}};

assign mul_FL_1_fu_1201_p3 = {{tmp_15_fu_1181_p4}, {7'd64}};

assign mul_FL_2_fu_1376_p3 = {{tmp_17_fu_1356_p4}, {5'd16}};

assign mul_FL_3_fu_1559_p3 = {{tmp_19_fu_1539_p4}, {3'd4}};

assign mul_FL_4_fu_1718_p3 = {{trunc_ln283_4_fu_1714_p1}, {1'd1}};

assign mul_FL_fu_1087_p3 = {{tmp_32_reg_2112}, {9'd256}};

assign or_ln295_10_fu_1681_p2 = (icmp_ln295_26_fu_1592_p2 | and_ln295_7_fu_1612_p2);

assign or_ln295_11_fu_1687_p2 = (or_ln295_10_fu_1681_p2 | icmp_ln295_25_fu_1587_p2);

assign or_ln295_12_fu_1797_p2 = (icmp_ln295_30_fu_1767_p2 | and_ln295_8_fu_1782_p2);

assign or_ln295_13_fu_1803_p2 = (or_ln295_12_fu_1797_p2 | and_ln295_9_fu_1763_p2);

assign or_ln295_1_fu_529_p2 = (icmp_ln295_fu_479_p2 | and_ln295_fu_494_p2);

assign or_ln295_2_fu_696_p2 = (icmp_ln295_3_fu_631_p2 | and_ln295_1_fu_652_p2);

assign or_ln295_3_fu_807_p2 = (icmp_ln295_6_fu_743_p2 | and_ln295_2_fu_764_p2);

assign or_ln295_4_fu_919_p2 = (icmp_ln295_9_reg_2054 | and_ln295_3_fu_895_p2);

assign or_ln295_5_fu_1036_p2 = (icmp_ln295_12_fu_964_p2 | and_ln295_4_fu_988_p2);

assign or_ln295_6_fu_1315_p2 = (icmp_ln295_18_fu_1230_p2 | and_ln295_5_fu_1250_p2);

assign or_ln295_7_fu_1321_p2 = (or_ln295_6_fu_1315_p2 | icmp_ln295_17_fu_1225_p2);

assign or_ln295_8_fu_1498_p2 = (icmp_ln295_22_fu_1409_p2 | and_ln295_6_fu_1429_p2);

assign or_ln295_9_fu_1504_p2 = (or_ln295_8_fu_1498_p2 | icmp_ln295_21_fu_1404_p2);

assign or_ln295_fu_1105_p2 = (icmp_ln295_16_fu_1100_p2 | icmp_ln295_15_fu_1094_p2);

assign or_ln308_1_fu_1449_p2 = (icmp_ln308_6_fu_1439_p2 | and_ln308_1_fu_1444_p2);

assign or_ln308_2_fu_1632_p2 = (icmp_ln308_7_fu_1622_p2 | and_ln308_2_fu_1627_p2);

assign or_ln308_fu_1270_p2 = (icmp_ln308_5_fu_1260_p2 | and_ln308_fu_1265_p2);

assign p_neg7_fu_1288_p3 = ((delta_reg_2162[0:0] == 1'b1) ? 10'd1023 : 10'd0);

assign res_FH_10_fu_1174_p3 = ((or_ln295_fu_1105_p2[0:0] == 1'b1) ? res_FH_9_fu_1142_p4 : res_FH_8_reg_2106);

assign res_FH_11_fu_1306_p4 = {res_FH_10_reg_2145[10 - 1:4], |(1'd1), res_FH_10_reg_2145[2:0]};

assign res_FH_12_fu_1349_p3 = ((or_ln295_7_fu_1321_p2[0:0] == 1'b1) ? res_FH_11_fu_1306_p4 : res_FH_10_reg_2145);

assign res_FH_13_fu_1489_p4 = {res_FH_12_reg_2191[10 - 1:3], |(1'd1), res_FH_12_reg_2191[1:0]};

assign res_FH_14_fu_1532_p3 = ((or_ln295_9_fu_1504_p2[0:0] == 1'b1) ? res_FH_13_fu_1489_p4 : res_FH_12_reg_2191);

assign res_FH_15_fu_1672_p4 = {res_FH_14_reg_2237[10 - 1:2], |(1'd1), res_FH_14_reg_2237[0:0]};

assign res_FH_16_fu_1707_p3 = ((or_ln295_11_fu_1687_p2[0:0] == 1'b1) ? res_FH_15_fu_1672_p4 : res_FH_14_reg_2237);

assign res_FH_17_fu_1788_p4 = {res_FH_16_reg_2271[10-1:1], |(1'd1)};

assign res_FH_18_fu_1809_p3 = ((or_ln295_13_fu_1803_p2[0:0] == 1'b1) ? res_FH_17_fu_1788_p4 : res_FH_16_reg_2271);

assign res_FH_1_fu_686_p4 = {res_FH_fu_604_p3[10 - 1:9], |(1'd1), res_FH_fu_604_p3[7:0]};

assign res_FH_2_fu_716_p3 = ((or_ln295_2_fu_696_p2[0:0] == 1'b1) ? res_FH_1_fu_686_p4 : res_FH_fu_604_p3);

assign res_FH_3_fu_798_p4 = {res_FH_2_reg_2021[10 - 1:8], |(1'd1), res_FH_2_reg_2021[6:0]};

assign res_FH_4_fu_827_p3 = ((or_ln295_3_fu_807_p2[0:0] == 1'b1) ? res_FH_3_fu_798_p4 : res_FH_2_reg_2021);

assign res_FH_5_fu_910_p4 = {res_FH_4_reg_2043[10 - 1:7], |(1'd1), res_FH_4_reg_2043[5:0]};

assign res_FH_6_fu_937_p3 = ((or_ln295_4_fu_919_p2[0:0] == 1'b1) ? res_FH_5_fu_910_p4 : res_FH_4_reg_2043);

assign res_FH_7_fu_1026_p4 = {res_FH_6_fu_937_p3[10 - 1:6], |(1'd1), res_FH_6_fu_937_p3[4:0]};

assign res_FH_8_fu_1050_p3 = ((or_ln295_5_fu_1036_p2[0:0] == 1'b1) ? res_FH_7_fu_1026_p4 : res_FH_6_fu_937_p3);

assign res_FH_9_fu_1142_p4 = {res_FH_8_reg_2106[10 - 1:5], |(1'd1), res_FH_8_reg_2106[3:0]};

assign res_FH_fu_604_p3 = ((or_ln295_1_reg_1942[0:0] == 1'b1) ? 10'd512 : 10'd0);

assign res_I_1_fu_325_p3 = ((icmp_ln258_1_reg_1894[0:0] == 1'b1) ? select_ln216_reg_1888 : res_I_fu_310_p4);

assign res_I_2_fu_381_p4 = {res_I_1_fu_325_p3[5 - 1:2], |(1'd1), res_I_1_fu_325_p3[0:0]};

assign res_I_3_fu_399_p3 = ((icmp_ln258_2_fu_359_p2[0:0] == 1'b1) ? res_I_1_fu_325_p3 : res_I_2_fu_381_p4);

assign res_I_4_fu_460_p4 = {res_I_3_reg_1911[5-1:1], |(1'd1)};

assign res_I_5_fu_469_p3 = ((icmp_ln258_3_reg_1917[0:0] == 1'b1) ? res_I_3_reg_1911 : res_I_4_fu_460_p4);

assign res_I_6_fu_1834_p2 = (res_I_5_reg_1931_pp0_iter9_reg + 5'd1);

assign res_I_7_fu_1839_p3 = ((tmp_39_fu_1826_p3[0:0] == 1'b1) ? res_I_6_fu_1834_p2 : res_I_5_reg_1931_pp0_iter9_reg);

assign res_I_fu_310_p4 = {select_ln216_reg_1888[5 - 1:3], |(1'd1), select_ln216_reg_1888[1:0]};

assign select_ln216_1_fu_252_p3 = ((icmp_ln258_fu_214_p2[0:0] == 1'b1) ? 2'd0 : 2'd2);

assign select_ln216_fu_244_p3 = ((icmp_ln258_fu_214_p2[0:0] == 1'b1) ? 5'd0 : 5'd8);

assign select_ln319_1_fu_1650_p3 = ((delta_2_reg_2254[0:0] == 1'b1) ? 8'd255 : 8'd0);

assign select_ln319_fu_1467_p3 = ((delta_1_reg_2208[0:0] == 1'b1) ? 9'd511 : 9'd0);

assign sext_ln319_1_fu_1663_p1 = $signed(sub_ln319_2_fu_1657_p2);

assign sext_ln319_fu_1480_p1 = $signed(sub_ln319_1_fu_1474_p2);

assign sub_ln263_1_fu_365_p2 = (tmp_8_fu_347_p3 - zext_ln258_2_fu_355_p1);

assign sub_ln263_2_fu_429_p2 = (trunc_ln258_fu_415_p1 - zext_ln258_3_fu_419_p1);

assign sub_ln263_fu_286_p2 = (tmp_2_fu_268_p3 - zext_ln258_1_fu_276_p1);

assign sub_ln319_1_fu_1474_p2 = (select_ln319_fu_1467_p3 - zext_ln285_2_fu_1400_p1);

assign sub_ln319_2_fu_1657_p2 = (select_ln319_1_fu_1650_p3 - zext_ln285_4_fu_1583_p1);

assign sub_ln319_fu_1295_p2 = (p_neg7_fu_1288_p3 - zext_ln285_fu_1221_p1);

assign tmp_10_fu_834_p3 = {{res_FH_4_fu_827_p3[9:6]}};

assign tmp_11_fu_944_p3 = {{res_FH_6_fu_937_p3[9:5]}};

assign tmp_15_fu_1181_p4 = {{res_FH_10_fu_1174_p3[5:3]}};

assign tmp_17_fu_1356_p4 = {{res_FH_12_fu_1349_p3[6:2]}};

assign tmp_19_fu_1539_p4 = {{res_FH_14_fu_1532_p3[7:1]}};

assign tmp_1_fu_200_p4 = {{x_int_reg[17:15]}};

assign tmp_23_fu_1846_p4 = {{add_ln338_fu_1820_p2[9:1]}};

assign tmp_2_fu_268_p3 = {{x_l_I_1_fu_236_p3[8:4]}};

assign tmp_39_fu_1826_p3 = add_ln338_fu_1820_p2[32'd10];

assign tmp_3_fu_182_p4 = {{x_int_reg[17:9]}};

assign tmp_4_fu_339_p3 = {{tmp_5_fu_331_p3}, {1'd1}};

assign tmp_5_fu_331_p3 = {{res_I_1_fu_325_p3[4:1]}};

assign tmp_6_fu_407_p3 = {{res_I_3_fu_399_p3}, {1'd1}};

assign tmp_7_fu_260_p3 = {{select_ln216_1_fu_252_p3}, {1'd1}};

assign tmp_8_fu_347_p3 = {{x_l_I_5_fu_319_p3[7:2]}};

assign tmp_9_fu_611_p3 = {{res_FH_fu_604_p3[9:8]}};

assign tmp_fu_1746_p3 = x_read_reg_1872_pp0_iter9_reg[32'd17];

assign trunc_ln213_fu_196_p1 = x_int_reg[8:0];

assign trunc_ln258_fu_415_p1 = x_l_I_7_fu_391_p3[6:0];

assign trunc_ln283_1_fu_564_p1 = res_I_5_fu_469_p3[1:0];

assign trunc_ln283_2_fu_578_p1 = res_I_5_fu_469_p3[2:0];

assign trunc_ln283_3_fu_592_p1 = res_I_5_fu_469_p3[3:0];

assign trunc_ln283_4_fu_1714_p1 = res_FH_16_fu_1707_p3[8:0];

assign trunc_ln283_fu_550_p1 = res_I_5_fu_469_p3[0:0];

assign x_l_FH_11_fu_1137_p2 = (x_l_FH_24_reg_2099 + xor_ln319_fu_1131_p2);

assign x_l_FH_13_fu_1301_p2 = (sub_ln319_fu_1295_p2 + x_l_FH_25_reg_2129);

assign x_l_FH_15_fu_1484_p2 = ($signed(sext_ln319_fu_1480_p1) + $signed(x_l_FH_26_reg_2175));

assign x_l_FH_17_fu_1693_p3 = ((or_ln295_11_fu_1687_p2[0:0] == 1'b1) ? x_l_FH_18_fu_1667_p2 : x_l_FH_27_reg_2221);

assign x_l_FH_18_fu_1667_p2 = ($signed(sext_ln319_1_fu_1663_p1) + $signed(x_l_FH_27_reg_2221));

assign x_l_FH_19_fu_453_p3 = {{trunc_ln213_reg_1877_pp0_iter1_reg}, {1'd0}};

assign x_l_FH_20_fu_542_p3 = ((or_ln295_1_fu_529_p2[0:0] == 1'b1) ? x_l_FH_fu_517_p2 : x_l_FH_19_fu_453_p3);

assign x_l_FH_21_fu_709_p3 = ((or_ln295_2_fu_696_p2[0:0] == 1'b1) ? x_l_FH_3_fu_675_p2 : x_l_FH_20_reg_1956);

assign x_l_FH_22_fu_820_p3 = ((or_ln295_3_fu_807_p2[0:0] == 1'b1) ? x_l_FH_5_fu_787_p2 : x_l_FH_21_reg_2013);

assign x_l_FH_23_fu_931_p3 = ((or_ln295_4_fu_919_p2[0:0] == 1'b1) ? x_l_FH_7_reg_2079 : x_l_FH_22_reg_2038);

assign x_l_FH_24_fu_1042_p3 = ((or_ln295_5_fu_1036_p2[0:0] == 1'b1) ? x_l_FH_9_fu_1014_p2 : x_l_FH_23_fu_931_p3);

assign x_l_FH_25_fu_1159_p3 = ((or_ln295_fu_1105_p2[0:0] == 1'b1) ? x_l_FH_11_fu_1137_p2 : x_l_FH_24_reg_2099);

assign x_l_FH_26_fu_1335_p3 = ((or_ln295_7_fu_1321_p2[0:0] == 1'b1) ? x_l_FH_13_fu_1301_p2 : x_l_FH_25_reg_2129);

assign x_l_FH_27_fu_1518_p3 = ((or_ln295_9_fu_1504_p2[0:0] == 1'b1) ? x_l_FH_15_fu_1484_p2 : x_l_FH_26_reg_2175);

assign x_l_FH_3_fu_675_p2 = (x_l_FH_20_reg_1956 - mul_FH_fu_619_p4);

assign x_l_FH_5_fu_787_p2 = (x_l_FH_21_reg_2013 - mul_FH_1_fu_732_p4);

assign x_l_FH_7_fu_884_p2 = (x_l_FH_22_fu_820_p3 - mul_FH_2_fu_842_p4);

assign x_l_FH_9_fu_1014_p2 = (x_l_FH_23_fu_931_p3 - mul_FH_3_fu_952_p4);

assign x_l_FH_fu_517_p2 = ($signed(x_l_FH_19_fu_453_p3) + $signed(10'd768));

assign x_l_FL_10_fu_1525_p3 = ((or_ln295_9_fu_1504_p2[0:0] == 1'b1) ? x_l_FL_4_fu_1435_p2 : x_l_FL_9_reg_2184);

assign x_l_FL_2_fu_1256_p2 = (x_l_FL_8_reg_2138 - mul_FL_1_reg_2156);

assign x_l_FL_4_fu_1435_p2 = (x_l_FL_9_reg_2184 - mul_FL_2_reg_2202);

assign x_l_FL_6_fu_1618_p2 = (x_l_FL_10_reg_2230 - mul_FL_3_reg_2248);

assign x_l_FL_7_fu_1700_p3 = ((or_ln295_11_fu_1687_p2[0:0] == 1'b1) ? x_l_FL_6_fu_1618_p2 : x_l_FL_10_reg_2230);

assign x_l_FL_8_fu_1166_p3 = ((or_ln295_fu_1105_p2[0:0] == 1'b1) ? x_l_FL_fu_1111_p2 : 10'd0);

assign x_l_FL_9_fu_1342_p3 = ((or_ln295_7_fu_1321_p2[0:0] == 1'b1) ? x_l_FL_2_fu_1256_p2 : x_l_FL_8_reg_2138);

assign x_l_FL_fu_1111_p2 = (10'd0 - mul_FL_fu_1087_p3);

assign x_l_I_10_fu_505_p2 = ($signed(x_l_I_9_reg_1922) + $signed(12'd4095));

assign x_l_I_11_fu_523_p2 = (x_l_I_3_fu_510_p3 - zext_ln295_fu_475_p1);

assign x_l_I_12_fu_663_p2 = ($signed(x_l_I_4_reg_1947) + $signed(12'd4095));

assign x_l_I_13_fu_668_p3 = ((icmp_ln308_1_fu_658_p2[0:0] == 1'b1) ? x_l_I_12_fu_663_p2 : x_l_I_4_reg_1947);

assign x_l_I_14_fu_680_p2 = (x_l_I_13_fu_668_p3 - zext_ln295_1_fu_628_p1);

assign x_l_I_15_fu_702_p3 = ((or_ln295_2_fu_696_p2[0:0] == 1'b1) ? x_l_I_14_fu_680_p2 : x_l_I_4_reg_1947);

assign x_l_I_16_fu_775_p2 = ($signed(x_l_I_15_reg_2004) + $signed(12'd4095));

assign x_l_I_17_fu_780_p3 = ((icmp_ln308_2_fu_770_p2[0:0] == 1'b1) ? x_l_I_16_fu_775_p2 : x_l_I_15_reg_2004);

assign x_l_I_18_fu_792_p2 = (x_l_I_17_fu_780_p3 - zext_ln295_2_fu_740_p1);

assign x_l_I_19_fu_813_p3 = ((or_ln295_3_fu_807_p2[0:0] == 1'b1) ? x_l_I_18_fu_792_p2 : x_l_I_15_reg_2004);

assign x_l_I_1_fu_236_p3 = ((icmp_ln258_fu_214_p2[0:0] == 1'b1) ? zext_ln212_fu_192_p1 : x_l_I_fu_226_p4);

assign x_l_I_20_fu_878_p2 = ($signed(x_l_I_19_fu_813_p3) + $signed(12'd4095));

assign x_l_I_21_fu_900_p3 = ((icmp_ln308_3_reg_2069[0:0] == 1'b1) ? x_l_I_20_reg_2074 : x_l_I_19_reg_2032);

assign x_l_I_22_fu_905_p2 = (x_l_I_21_fu_900_p3 - zext_ln295_3_reg_2049);

assign x_l_I_23_fu_924_p3 = ((or_ln295_4_fu_919_p2[0:0] == 1'b1) ? x_l_I_22_fu_905_p2 : x_l_I_19_reg_2032);

assign x_l_I_24_fu_1000_p2 = ($signed(x_l_I_23_fu_924_p3) + $signed(12'd4095));

assign x_l_I_25_fu_1006_p3 = ((icmp_ln308_4_fu_994_p2[0:0] == 1'b1) ? x_l_I_24_fu_1000_p2 : x_l_I_23_fu_924_p3);

assign x_l_I_26_fu_1020_p2 = (x_l_I_25_fu_1006_p3 - zext_ln295_4_fu_961_p1);

assign x_l_I_27_fu_1076_p3 = ((or_ln295_5_reg_2094[0:0] == 1'b1) ? x_l_I_26_reg_2089 : x_l_I_23_reg_2084);

assign x_l_I_28_fu_1117_p2 = ($signed(x_l_I_27_fu_1076_p3) + $signed(12'd4095));

assign x_l_I_29_fu_1123_p3 = ((icmp_ln295_16_fu_1100_p2[0:0] == 1'b1) ? x_l_I_27_fu_1076_p3 : x_l_I_28_fu_1117_p2);

assign x_l_I_2_fu_302_p4 = {{x_l_I_1_reg_1882[11:9]}, {sub_ln263_reg_1900}, {x_l_I_1_reg_1882[3:0]}};

assign x_l_I_30_fu_1151_p3 = ((or_ln295_fu_1105_p2[0:0] == 1'b1) ? x_l_I_29_fu_1123_p3 : 12'd0);

assign x_l_I_31_fu_1276_p2 = ($signed(x_l_I_30_reg_2122) + $signed(12'd4095));

assign x_l_I_32_fu_1281_p3 = ((or_ln308_fu_1270_p2[0:0] == 1'b1) ? x_l_I_31_fu_1276_p2 : x_l_I_30_reg_2122);

assign x_l_I_33_fu_1327_p3 = ((or_ln295_7_fu_1321_p2[0:0] == 1'b1) ? x_l_I_32_fu_1281_p3 : 12'd0);

assign x_l_I_34_fu_1455_p2 = ($signed(x_l_I_33_reg_2168) + $signed(12'd4095));

assign x_l_I_35_fu_1460_p3 = ((or_ln308_1_fu_1449_p2[0:0] == 1'b1) ? x_l_I_34_fu_1455_p2 : x_l_I_33_reg_2168);

assign x_l_I_36_fu_1510_p3 = ((or_ln295_9_fu_1504_p2[0:0] == 1'b1) ? x_l_I_35_fu_1460_p3 : 12'd0);

assign x_l_I_37_fu_1638_p2 = ($signed(x_l_I_36_reg_2214) + $signed(12'd4095));

assign x_l_I_38_fu_1643_p3 = ((or_ln308_2_fu_1632_p2[0:0] == 1'b1) ? x_l_I_37_fu_1638_p2 : x_l_I_36_reg_2214);

assign x_l_I_3_fu_510_p3 = ((icmp_ln308_fu_500_p2[0:0] == 1'b1) ? x_l_I_10_fu_505_p2 : x_l_I_9_reg_1922);

assign x_l_I_4_fu_535_p3 = ((or_ln295_1_fu_529_p2[0:0] == 1'b1) ? x_l_I_11_fu_523_p2 : x_l_I_9_reg_1922);

assign x_l_I_5_fu_319_p3 = ((icmp_ln258_1_reg_1894[0:0] == 1'b1) ? x_l_I_1_reg_1882 : x_l_I_2_fu_302_p4);

assign x_l_I_6_fu_371_p4 = {{x_l_I_5_fu_319_p3[11:8]}, {sub_ln263_1_fu_365_p2}, {x_l_I_5_fu_319_p3[1:0]}};

assign x_l_I_7_fu_391_p3 = ((icmp_ln258_2_fu_359_p2[0:0] == 1'b1) ? x_l_I_5_fu_319_p3 : x_l_I_6_fu_371_p4);

assign x_l_I_8_fu_435_p4 = {{x_l_I_7_fu_391_p3[11:7]}, {sub_ln263_2_fu_429_p2}};

assign x_l_I_9_fu_445_p3 = ((icmp_ln258_3_fu_423_p2[0:0] == 1'b1) ? x_l_I_7_fu_391_p3 : x_l_I_8_fu_435_p4);

assign x_l_I_fu_226_p4 = {{zext_ln212_fu_192_p1[11:10]}, {add_ln263_fu_220_p2}, {zext_ln212_fu_192_p1[5:0]}};

assign xor_ln295_1_fu_758_p2 = (icmp_ln295_8_fu_753_p2 ^ 1'd1);

assign xor_ln295_2_fu_890_p2 = (icmp_ln295_11_reg_2064 ^ 1'd1);

assign xor_ln295_3_fu_982_p2 = (icmp_ln295_14_fu_976_p2 ^ 1'd1);

assign xor_ln295_4_fu_1244_p2 = (icmp_ln295_20_fu_1240_p2 ^ 1'd1);

assign xor_ln295_5_fu_1423_p2 = (icmp_ln295_24_fu_1419_p2 ^ 1'd1);

assign xor_ln295_6_fu_1606_p2 = (icmp_ln295_28_fu_1602_p2 ^ 1'd1);

assign xor_ln295_7_fu_1777_p2 = (icmp_ln295_32_reg_2287 ^ 1'd1);

assign xor_ln295_fu_646_p2 = (icmp_ln295_5_fu_641_p2 ^ 1'd1);

assign xor_ln319_fu_1131_p2 = (mul_FH_4_fu_1081_p3 ^ 10'd1023);

assign zext_ln212_fu_192_p1 = tmp_3_fu_182_p4;

assign zext_ln258_1_fu_276_p1 = tmp_7_fu_260_p3;

assign zext_ln258_2_fu_355_p1 = tmp_4_fu_339_p3;

assign zext_ln258_3_fu_419_p1 = tmp_6_fu_407_p3;

assign zext_ln258_fu_210_p1 = tmp_1_fu_200_p4;

assign zext_ln285_1_fu_1396_p1 = mul_FH_6_fu_1390_p3;

assign zext_ln285_2_fu_1400_p1 = mul_FH_6_fu_1390_p3;

assign zext_ln285_3_fu_1579_p1 = mul_FH_7_fu_1573_p3;

assign zext_ln285_4_fu_1583_p1 = mul_FH_7_fu_1573_p3;

assign zext_ln285_5_fu_1759_p1 = mul_FH_8_fu_1753_p3;

assign zext_ln285_fu_1221_p1 = mul_FH_5_fu_1215_p3;

assign zext_ln295_1_fu_628_p1 = tmp_12_reg_1969;

assign zext_ln295_2_fu_740_p1 = tmp_13_reg_1979_pp0_iter3_reg;

assign zext_ln295_3_fu_851_p1 = tmp_14_reg_1989_pp0_iter3_reg;

assign zext_ln295_4_fu_961_p1 = tmp_30_reg_1999_pp0_iter4_reg;

assign zext_ln295_fu_475_p1 = res_I_5_fu_469_p3;

assign zext_ln338_fu_1816_p1 = res_FH_18_fu_1809_p3;

always @ (posedge ap_clk) begin
    select_ln216_reg_1888[2:0] <= 3'b000;
    select_ln216_reg_1888[4] <= 1'b0;
    x_l_FH_20_reg_1956[0] <= 1'b0;
    x_l_FH_21_reg_2013[0] <= 1'b0;
    x_l_FH_22_reg_2038[0] <= 1'b0;
    zext_ln295_3_reg_2049[11:2] <= 10'b0000000000;
    x_l_FH_7_reg_2079[0] <= 1'b0;
    x_l_FL_8_reg_2138[7:0] <= 8'b00000000;
    mul_FL_1_reg_2156[6:0] <= 7'b1000000;
    x_l_FL_9_reg_2184[5:0] <= 6'b000000;
    mul_FL_2_reg_2202[4:0] <= 5'b10000;
    x_l_FL_10_reg_2230[3:0] <= 4'b0000;
    mul_FL_3_reg_2248[2:0] <= 3'b100;
end

endmodule //compute_c_sqrt_fixed_18_9_s
